### ISSUE TITLE
Compiled download?

### ISSUE THREAD

**Issue by cmccall** [thesaadismail/mums-the-word#1]
Is there a compiled version of this available for download somewhere? I didn't see it on your site nor can I install XCode on this particular computer.

**Comment by thesaadismail** [comment]
Hey cmccall, Sorry about the delayed response! I don't have a compiled version on github but let me build and upload it. I'll get back to you soon.

**Comment by thesaadismail** [comment]
Hey cmcall, My apologies for the delayed response again. This past few weeks have been a little busy! I have created an alpha build and uploaded it to github. Here is a link to it: https://github.com/thesaadismail/mums-the-word/releases/tag/v0.1

I have also added in additional details and current issues in the link above. Let me know if you have any questions!
